CC = gcc
CFLAGS = -ansi -Wall -g -O0 -Wwrite-strings -Wshadow -fstack-protector-all 
PROGS = nm_example

all: $(PROGS)

nm_example.o:

clean:
	@echo "Cleaning executables and .o files"
	@rm -f *.o $(PROGS) a.out
