CC = gcc
CFLAGS = -ansi -pedantic-errors -Wall -Werror
LDFLAGS = -lpthread
PROGS = threadsBasics threadsRetRandomValue threadsRetSqrValue threadsSeveral

all: $(PROGS)

clean:
	@echo "Cleaning executables and .o files"
	@rm -f *.o $(PROGS) a.out
